import { SEO } from '../../components/SEO';

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto py-12 prose prose-slate">
      <SEO title="Terms of Service" description="Terms of Service for FinCalcPro." />
      <h1>Terms of Service</h1>
      <p>Last updated: {new Date().toLocaleDateString()}</p>
      
      <h2>1. Agreement to Terms</h2>
      <p>By accessing or using FinCalcPro, you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>

      <h2>2. Informational Purposes Only</h2>
      <p>All calculations, projections, and reports generated by FinCalcPro are for informational and educational purposes only. They do not constitute financial, legal, or tax advice. You should consult a licensed financial advisor before making actual financial decisions.</p>

      <h2>3. Intellectual Property</h2>
      <p>The Service and its original content, features, and functionality are and will remain the exclusive property of FinCalcPro and its licensors.</p>

      <h2>4. Third-Party Links</h2>
      <p>Our Service may contain links to third-party web sites or services (including AdSense advertisements) that are not owned or controlled by FinCalcPro. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third party web sites or services.</p>

      <h2>5. Limitation Of Liability</h2>
      <p>In no event shall FinCalcPro, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your use of the calculators.</p>
    </div>
  );
}
